name: shape_classifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - poetry=1.1.8
  - dataclasses=0.8
  - pytorch=1.9.0
  - cudatoolkit=11.1
  - torchaudio
  - torchvision
  - pytorch-lightning
  - torchmetrics
